DROP TABLE IF EXISTS SALE;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;
-- 2. TABLA CUSTOMER
CREATE TABLE CUSTOMER (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_gender VARCHAR(10),
    customer_age_group VARCHAR(30),
    customer_segment VARCHAR(30),
    region VARCHAR(100)
);
-- 3. TABLA PRODUCT
CREATE TABLE PRODUCT (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(250),
    unit_price NUMERIC(10, 2),
    category VARCHAR(30),
    brand VARCHAR(15)
);
-- 4. TABLA TRANSACTIONS
CREATE TABLE TRANSACTIONS (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES CUSTOMER(customer_id),
    transaction_date DATE,
    payment_method VARCHAR(50),
    sales_channel VARCHAR(50)
);
-- 5. TABLA SALE
CREATE TABLE SALE (
    transaction_id INTEGER REFERENCES TRANSACTIONS(transaction_id),
    product_id INTEGER REFERENCES PRODUCT(product_id),
    quantity INT,
    discount_pct NUMERIC(5, 2), 
    sales_amount NUMERIC(10, 2),
    PRIMARY KEY (transaction_id, product_id)
);
-- Wrangling SQL Script for Retail Data Warehouse